name: Update Language Stats

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # Executa diariamente à meia-noite

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Update language stats in README
        uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
